//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Vector2 p_default_Movement;
        
        private static SteamVR_Action_Vector2 p_default_Turn;
        
        private static SteamVR_Action_Boolean p_default_Shoot;
        
        private static SteamVR_Action_Boolean p_default_AltShoot;
        
        private static SteamVR_Action_Boolean p_default_Jump;
        
        private static SteamVR_Action_Boolean p_default_Slide;
        
        private static SteamVR_Action_Boolean p_default_Dash;
        
        private static SteamVR_Action_Boolean p_default_Escape;
        
        private static SteamVR_Action_Boolean p_default_OpenWeaponWheel;
        
        private static SteamVR_Action_Boolean p_default_ChangeWeaponVariation;
        
        private static SteamVR_Action_Vector2 p_default_IterateWeapon;
        
        private static SteamVR_Action_Boolean p_default_SwapHand;
        
        private static SteamVR_Action_Boolean p_default_Slot1;
        
        private static SteamVR_Action_Boolean p_default_Slot2;
        
        private static SteamVR_Action_Boolean p_default_Slot3;
        
        private static SteamVR_Action_Boolean p_default_Slot4;
        
        private static SteamVR_Action_Boolean p_default_Slot5;
        
        private static SteamVR_Action_Boolean p_default_Slot6;
        
        private static SteamVR_Action_Boolean p_default_Slot7;
        
        private static SteamVR_Action_Boolean p_default_Slot8;
        
        private static SteamVR_Action_Boolean p_default_Slot9;
        
        private static SteamVR_Action_Boolean p_default_Slot0;
        
        private static SteamVR_Action_Boolean p_default_Whiplash;
        
        private static SteamVR_Action_Boolean p_default_Punch;
        
        private static SteamVR_Action_Pose p_default_LeftPose;
        
        private static SteamVR_Action_Pose p_default_RightPose;
        
        private static SteamVR_Action_Vector2 p_default_WeaponWheelScroll;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Vector2 default_Movement
        {
            get
            {
                return SteamVR_Actions.p_default_Movement.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_Turn
        {
            get
            {
                return SteamVR_Actions.p_default_Turn.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Shoot
        {
            get
            {
                return SteamVR_Actions.p_default_Shoot.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_AltShoot
        {
            get
            {
                return SteamVR_Actions.p_default_AltShoot.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Jump
        {
            get
            {
                return SteamVR_Actions.p_default_Jump.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slide
        {
            get
            {
                return SteamVR_Actions.p_default_Slide.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Dash
        {
            get
            {
                return SteamVR_Actions.p_default_Dash.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Escape
        {
            get
            {
                return SteamVR_Actions.p_default_Escape.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_OpenWeaponWheel
        {
            get
            {
                return SteamVR_Actions.p_default_OpenWeaponWheel.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_ChangeWeaponVariation
        {
            get
            {
                return SteamVR_Actions.p_default_ChangeWeaponVariation.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_IterateWeapon
        {
            get
            {
                return SteamVR_Actions.p_default_IterateWeapon.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Boolean default_SwapHand
        {
            get
            {
                return SteamVR_Actions.p_default_SwapHand.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot1
        {
            get
            {
                return SteamVR_Actions.p_default_Slot1.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot2
        {
            get
            {
                return SteamVR_Actions.p_default_Slot2.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot3
        {
            get
            {
                return SteamVR_Actions.p_default_Slot3.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot4
        {
            get
            {
                return SteamVR_Actions.p_default_Slot4.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot5
        {
            get
            {
                return SteamVR_Actions.p_default_Slot5.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot6
        {
            get
            {
                return SteamVR_Actions.p_default_Slot6.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot7
        {
            get
            {
                return SteamVR_Actions.p_default_Slot7.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot8
        {
            get
            {
                return SteamVR_Actions.p_default_Slot8.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot9
        {
            get
            {
                return SteamVR_Actions.p_default_Slot9.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Slot0
        {
            get
            {
                return SteamVR_Actions.p_default_Slot0.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Whiplash
        {
            get
            {
                return SteamVR_Actions.p_default_Whiplash.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Punch
        {
            get
            {
                return SteamVR_Actions.p_default_Punch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose default_LeftPose
        {
            get
            {
                return SteamVR_Actions.p_default_LeftPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Pose default_RightPose
        {
            get
            {
                return SteamVR_Actions.p_default_RightPose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_WeaponWheelScroll
        {
            get
            {
                return SteamVR_Actions.p_default_WeaponWheelScroll.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Movement,
                    SteamVR_Actions.default_Turn,
                    SteamVR_Actions.default_Shoot,
                    SteamVR_Actions.default_AltShoot,
                    SteamVR_Actions.default_Jump,
                    SteamVR_Actions.default_Slide,
                    SteamVR_Actions.default_Dash,
                    SteamVR_Actions.default_Escape,
                    SteamVR_Actions.default_OpenWeaponWheel,
                    SteamVR_Actions.default_ChangeWeaponVariation,
                    SteamVR_Actions.default_IterateWeapon,
                    SteamVR_Actions.default_SwapHand,
                    SteamVR_Actions.default_Slot1,
                    SteamVR_Actions.default_Slot2,
                    SteamVR_Actions.default_Slot3,
                    SteamVR_Actions.default_Slot4,
                    SteamVR_Actions.default_Slot5,
                    SteamVR_Actions.default_Slot6,
                    SteamVR_Actions.default_Slot7,
                    SteamVR_Actions.default_Slot8,
                    SteamVR_Actions.default_Slot9,
                    SteamVR_Actions.default_Slot0,
                    SteamVR_Actions.default_Whiplash,
                    SteamVR_Actions.default_Punch,
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose,
                    SteamVR_Actions.default_WeaponWheelScroll,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Movement,
                    SteamVR_Actions.default_Turn,
                    SteamVR_Actions.default_Shoot,
                    SteamVR_Actions.default_AltShoot,
                    SteamVR_Actions.default_Jump,
                    SteamVR_Actions.default_Slide,
                    SteamVR_Actions.default_Dash,
                    SteamVR_Actions.default_Escape,
                    SteamVR_Actions.default_OpenWeaponWheel,
                    SteamVR_Actions.default_ChangeWeaponVariation,
                    SteamVR_Actions.default_IterateWeapon,
                    SteamVR_Actions.default_SwapHand,
                    SteamVR_Actions.default_Slot1,
                    SteamVR_Actions.default_Slot2,
                    SteamVR_Actions.default_Slot3,
                    SteamVR_Actions.default_Slot4,
                    SteamVR_Actions.default_Slot5,
                    SteamVR_Actions.default_Slot6,
                    SteamVR_Actions.default_Slot7,
                    SteamVR_Actions.default_Slot8,
                    SteamVR_Actions.default_Slot9,
                    SteamVR_Actions.default_Slot0,
                    SteamVR_Actions.default_Whiplash,
                    SteamVR_Actions.default_Punch,
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose,
                    SteamVR_Actions.default_WeaponWheelScroll};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_LeftPose,
                    SteamVR_Actions.default_RightPose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_Shoot,
                    SteamVR_Actions.default_AltShoot,
                    SteamVR_Actions.default_Jump,
                    SteamVR_Actions.default_Slide,
                    SteamVR_Actions.default_Dash,
                    SteamVR_Actions.default_Escape,
                    SteamVR_Actions.default_OpenWeaponWheel,
                    SteamVR_Actions.default_ChangeWeaponVariation,
                    SteamVR_Actions.default_SwapHand,
                    SteamVR_Actions.default_Slot1,
                    SteamVR_Actions.default_Slot2,
                    SteamVR_Actions.default_Slot3,
                    SteamVR_Actions.default_Slot4,
                    SteamVR_Actions.default_Slot5,
                    SteamVR_Actions.default_Slot6,
                    SteamVR_Actions.default_Slot7,
                    SteamVR_Actions.default_Slot8,
                    SteamVR_Actions.default_Slot9,
                    SteamVR_Actions.default_Slot0,
                    SteamVR_Actions.default_Whiplash,
                    SteamVR_Actions.default_Punch};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_Movement,
                    SteamVR_Actions.default_Turn,
                    SteamVR_Actions.default_IterateWeapon,
                    SteamVR_Actions.default_WeaponWheelScroll};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Movement,
                    SteamVR_Actions.default_Turn,
                    SteamVR_Actions.default_Shoot,
                    SteamVR_Actions.default_AltShoot,
                    SteamVR_Actions.default_Jump,
                    SteamVR_Actions.default_Slide,
                    SteamVR_Actions.default_Dash,
                    SteamVR_Actions.default_Escape,
                    SteamVR_Actions.default_OpenWeaponWheel,
                    SteamVR_Actions.default_ChangeWeaponVariation,
                    SteamVR_Actions.default_IterateWeapon,
                    SteamVR_Actions.default_SwapHand,
                    SteamVR_Actions.default_Slot1,
                    SteamVR_Actions.default_Slot2,
                    SteamVR_Actions.default_Slot3,
                    SteamVR_Actions.default_Slot4,
                    SteamVR_Actions.default_Slot5,
                    SteamVR_Actions.default_Slot6,
                    SteamVR_Actions.default_Slot7,
                    SteamVR_Actions.default_Slot8,
                    SteamVR_Actions.default_Slot9,
                    SteamVR_Actions.default_Slot0,
                    SteamVR_Actions.default_Whiplash,
                    SteamVR_Actions.default_Punch,
                    SteamVR_Actions.default_WeaponWheelScroll};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Movement = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Movement")));
            SteamVR_Actions.p_default_Turn = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/Turn")));
            SteamVR_Actions.p_default_Shoot = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Shoot")));
            SteamVR_Actions.p_default_AltShoot = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/AltShoot")));
            SteamVR_Actions.p_default_Jump = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Jump")));
            SteamVR_Actions.p_default_Slide = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slide")));
            SteamVR_Actions.p_default_Dash = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Dash")));
            SteamVR_Actions.p_default_Escape = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Escape")));
            SteamVR_Actions.p_default_OpenWeaponWheel = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/OpenWeaponWheel")));
            SteamVR_Actions.p_default_ChangeWeaponVariation = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/ChangeWeaponVariation")));
            SteamVR_Actions.p_default_IterateWeapon = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/IterateWeapon")));
            SteamVR_Actions.p_default_SwapHand = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/SwapHand")));
            SteamVR_Actions.p_default_Slot1 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot1")));
            SteamVR_Actions.p_default_Slot2 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot2")));
            SteamVR_Actions.p_default_Slot3 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot3")));
            SteamVR_Actions.p_default_Slot4 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot4")));
            SteamVR_Actions.p_default_Slot5 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot5")));
            SteamVR_Actions.p_default_Slot6 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot6")));
            SteamVR_Actions.p_default_Slot7 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot7")));
            SteamVR_Actions.p_default_Slot8 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot8")));
            SteamVR_Actions.p_default_Slot9 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot9")));
            SteamVR_Actions.p_default_Slot0 = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Slot0")));
            SteamVR_Actions.p_default_Whiplash = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Whiplash")));
            SteamVR_Actions.p_default_Punch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Punch")));
            SteamVR_Actions.p_default_LeftPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/LeftPose")));
            SteamVR_Actions.p_default_RightPose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/RightPose")));
            SteamVR_Actions.p_default_WeaponWheelScroll = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/WeaponWheelScroll")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
