//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Movement
        {
            get
            {
                return SteamVR_Actions.default_Movement;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Turn
        {
            get
            {
                return SteamVR_Actions.default_Turn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.default_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean AltShoot
        {
            get
            {
                return SteamVR_Actions.default_AltShoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean Jump
        {
            get
            {
                return SteamVR_Actions.default_Jump;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slide
        {
            get
            {
                return SteamVR_Actions.default_Slide;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dash
        {
            get
            {
                return SteamVR_Actions.default_Dash;
            }
        }
        
        public virtual SteamVR_Action_Boolean Escape
        {
            get
            {
                return SteamVR_Actions.default_Escape;
            }
        }
        
        public virtual SteamVR_Action_Pose LHP
        {
            get
            {
                return SteamVR_Actions.default_LHP;
            }
        }
        
        public virtual SteamVR_Action_Pose RHP
        {
            get
            {
                return SteamVR_Actions.default_RHP;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenWeaponWheel
        {
            get
            {
                return SteamVR_Actions.default_OpenWeaponWheel;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChangeWeaponVariation
        {
            get
            {
                return SteamVR_Actions.default_ChangeWeaponVariation;
            }
        }
        
        public virtual SteamVR_Action_Vector2 IterateWeapon
        {
            get
            {
                return SteamVR_Actions.default_IterateWeapon;
            }
        }
        
        public virtual SteamVR_Action_Boolean SwapHand
        {
            get
            {
                return SteamVR_Actions.default_SwapHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot1
        {
            get
            {
                return SteamVR_Actions.default_Slot1;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot2
        {
            get
            {
                return SteamVR_Actions.default_Slot2;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot3
        {
            get
            {
                return SteamVR_Actions.default_Slot3;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot4
        {
            get
            {
                return SteamVR_Actions.default_Slot4;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot5
        {
            get
            {
                return SteamVR_Actions.default_Slot5;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot6
        {
            get
            {
                return SteamVR_Actions.default_Slot6;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot7
        {
            get
            {
                return SteamVR_Actions.default_Slot7;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot8
        {
            get
            {
                return SteamVR_Actions.default_Slot8;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot9
        {
            get
            {
                return SteamVR_Actions.default_Slot9;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slot0
        {
            get
            {
                return SteamVR_Actions.default_Slot0;
            }
        }
        
        public virtual SteamVR_Action_Boolean Whiplash
        {
            get
            {
                return SteamVR_Actions.default_Whiplash;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
