//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 Movement
        {
            get
            {
                return SteamVR_Actions.default_Movement;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Turn
        {
            get
            {
                return SteamVR_Actions.default_Turn;
            }
        }
        
        public virtual SteamVR_Action_Boolean Shoot
        {
            get
            {
                return SteamVR_Actions.default_Shoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean AltShoot
        {
            get
            {
                return SteamVR_Actions.default_AltShoot;
            }
        }
        
        public virtual SteamVR_Action_Boolean OpenWeaponWheel
        {
            get
            {
                return SteamVR_Actions.default_OpenWeaponWheel;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.default_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean JumpSlam
        {
            get
            {
                return SteamVR_Actions.default_JumpSlam;
            }
        }
        
        public virtual SteamVR_Action_Boolean Slide
        {
            get
            {
                return SteamVR_Actions.default_Slide;
            }
        }
        
        public virtual SteamVR_Action_Boolean Dash
        {
            get
            {
                return SteamVR_Actions.default_Dash;
            }
        }
        
        public virtual SteamVR_Action_Boolean Pause
        {
            get
            {
                return SteamVR_Actions.default_Pause;
            }
        }
    }
}
